apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-stepa
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website-s
      url: http://gms-ops.net
    - title: Documentation-s
      url: https://gms-ops.net/docs
    - title: Storybook-s
      url: https://gms-ops.net/storybook
    - title: Discord Chat-s
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage-orig
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://gms-ops.net
spec:
  type: library
  owner: CNCF
  lifecycle: experimental

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: second-test-stepaa
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/techdocs-ref: value
    github.com/project-slug: stepa-ict/backstage-orig
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: vladimir.stepic@gms-ops.net
  lifecycle: experimental


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };

---
